### ISSUE TITLE
cant spawn boat after pull

### ISSUE THREAD

**Issue by xenfovn** [qbcore-framework/qb-diving#25]
pls check this pls

**Comment by Manliketjb** [comment]
think i'm having the same issue, can buy a boat but won't spawn once stored
![20211122093208_1](https://user-images.githubusercontent.com/82594996/142947368-c172018b-9700-4a34-8c95-e75e250effb1.jpg)

**Comment by kingofkingzcd** [comment]
same error but line 162

**Comment by kingofkingzcd** [comment]
got them to spawn. although you can just spawn in the same boat repeatedly. not real sure how to stop that.

**Comment by vulthrax** [comment]
kingofkingzcd how did you manage to get them out ?

**Comment by kingofkingzcd** [comment]
> kingofkingzcd how did you manage to get them out ?

if you look for docks in diving/garages there is a spot that says depot that should say docks instead. i actually ended up scrapping the boats out of qb-diving and adding them to vehicleshop and creating a boat impound for them.

**Comment by vulthrax** [comment]
This do fixes the spawn when you purchase a boat,  and if you buy a boat after this fix you can directly get in to the boat. But there is still a problem when the server is restarted and you take out your boat from the garage then the boat is always locked and i have to lockpick it. This does not happen if you buy a new boat after the restart.
