### ISSUE TITLE
[bug][fix] diving gear has Collision that the player not take damage

### ISSUE THREAD

**Issue by omar-othmann** [qbcore-framework/qb-diving#38]
i found a bug inside qb-diving, when you wear it you can't take headshot damage and backside

the script owner should fix it by:
`SetEntityCollision(MaskObject, false, false)`
put under this line `MaskObject = CreateObject(maskModel, 1.0, 1.0, 1.0, 1, 1, 0)`

and ` SetEntityCollision(TankObject, false, false)`
under this line `TankObject = CreateObject(tankModel, 1.0, 1.0, 1.0, 1, 1, 0)`

**Comment by ShomyTKD** [comment]
Great, this works, thank you! @omar-othmann I suggest you to create a pull request
