### ISSUE TITLE
Can't store boats

### ISSUE THREAD

**Issue by brynnie1** [qbcore-framework/qb-diving#40]
So I rent a boat, and when i'm finished I can't give it back or store it so it has to be left out
Also  when I buy boats from the dockyard , it takes the money from teh account but I can't store them

**Comment by Andyauk** [comment]
> So I rent a boat, and when i'm finished I can't give it back or store it so it has to be left out Also when I buy boats from the dockyard , it takes the money from teh account but I can't store them

your using an old copy, of diving, as the update doesn't have boats, so not sure its supported now.

**Comment by brynnie1** [comment]
Since updating the scripts boats have now gone so no longer supported
