### ISSUE TITLE
[SUGGESTION] drawtext question marks

### ISSUE THREAD

**Issue by nolanrp** [qbcore-framework/qb-diving#55]
After this resource was updated its impossible to find the location of the coral without scanning the bottom of the ocean for 20min.

I think adding back the small question marks would make this script better again

Thankyou

**Comment by GhostLegionRP** [comment]
have the same wish

**Comment by nzkfc** [comment]
Just updated ours and changed all the locations and added 7-10 new spots per zone and we couldn't work out why nothing was "spawning" ahaha.

Has to be something for players to see.

**Comment by nzkfc** [comment]
Ahh this was it...

`DrawMarker(32, CoralLocation.coords.x, CoralLocation.coords.y, CoralLocation.coords.z, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 1.0, 0.4, 255, 223, 0, 255, true, false, false, false, false, false, false)
                                if CoralDistance <= 1.5 then`

**Comment by BerkieBb** [comment]
Currently only location 1 has it's location set on an area with corals and the coral locations are on already spawned corals, so that is a start

**Comment by nzkfc** [comment]
Oh right, I guess the issue on our 200 pop iin NZ is people love to dive so
they go in social groups and split up.

**Comment by amgmacht** [comment]
Hey, is there anything new about the markers? as our players have a really hard time finding the points without a marker or spawn prop

**Comment by Sanriku-Gaming** [comment]
> Currently only location 1 has it's location set on an area with corals and the coral locations are on already spawned corals, so that is a start

So, with this in mind, is it possible for qb-target to spawn props in those box zones?

**Comment by BerkieBb** [comment]
I wanted to do it, but I didn't have the time, now I'm on vacation so I can't do it, if anyone else would do it, I'd be happy to review the PR and get it merged

**Comment by nzkfc** [comment]
> I wanted to do it, but I didn't have the time, now I'm on vacation so I can't do it, if anyone else would do it, I'd be happy to review the PR and get it merged

Ah right, ok well theres no rush I guess, enjoy ya holiday :)

**Comment by Sanriku-Gaming** [comment]
> I wanted to do it, but I didn't have the time, now I'm on vacation so I can't do it, if anyone else would do it, I'd be happy to review the PR and get it merged

So, I've rewritten a few things to get this working by spawning a prop (coral) in the boxes for each zone. (among other QoL functions like a drawtext function while underwater). I'm not familiar enough with github to make a pull request, if you wouldn't mind helping with that.

**Comment by nzkfc** [comment]
@Z3rio this was closed as completed but PR #60 is still open?

https://i.imgur.com/7vKnP5Y.jpeg

Other then that, seems to be working fine, just need something better than polyzones for players to actually find.

**Comment by Z3rio** [comment]
I will take a look at that PR aswell then, thanks for telling me.
It always says "closed as completed" when closing something :)
