### ISSUE TITLE
[BUG] Longer diving tank time?

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-diving#56]
**Describe the bug**
Before the most recent version (as ov 17th June) the tank seems to last a longer time, at the moment we can only do one dive for a single coral before it tells us we have no air? Used to be able to at least do one entire zone before it ran out.

**To Reproduce**
1. Go diving
2. Dive to one spot and it should ping pretty quickly that you have 1 min of air left.

**Expected behavior**
I guess more air? I did read that tank time is limited in gtav so you can't change it potentially?

**Questions (please complete the following information):**
 - When you last updated: 17th June 2022
 - Are you using custom resource? which ones? Nothing that affects tank time
 - Have you renamed `qb-` to something custom? Nope

**Comment by uShifty** [comment]
Currently now you can swim for 3 minutes by default, If you want to have more air in your oxygen tank you can edit your qb-shops config and make it so for diving tanks have a meta data value greater than 200 like this, `info = { oxygen = 200 },`

**Comment by amgmacht** [comment]
where exactly in the config do I put that? I can't get it?

**Comment by nzkfc** [comment]
Put that into the info line inside the product for diving tank where the
diving tank is listed in the shop products.
