### ISSUE TITLE
Boathouse

### ISSUE THREAD

**Issue by danny2004lam** [qbcore-framework/qb-diving#6]
Can't store boat in boathouse
The mysql database doesn't change

**Comment by capocsgo** [comment]
Yes, when you go store a boat, it actually sends it to the Depot

**Comment by danny2004lam** [comment]
AddEventHandler('qb-diving:server:SetBoatState', function(plate, state, boathouse)
i dont know why but when i print the plate it has a space
example : the boat's plate is QB123, it will print QB 123 instead of QB123

Solution: replace all the plate with this variable
local trueplate = string.gsub(plate, "%s+", "")

Sorry for my bad english
