### ISSUE TITLE
[BUG] Issue with the diving gear

### ISSUE THREAD

**Issue by GameN4life** [qbcore-framework/qb-diving#66]
The old diving doesnt work with the update, it just gives the error of "you need an oxygen tube"

**Comment by ahmed608** [comment]
> The old diving doesnt work with the update, it just gives the error of "you need an oxygen tube"

this is not error you need to fill tube with item 
diving_fill @GameN4life

**Comment by ahmed608** [comment]
see this video
@GameN4life

**Comment by GameN4life** [comment]
I dont see the video

**Comment by ahmed608** [comment]
> 

https://www.youtube.com/watch?v=pPYsy1tKPVM @GameN4life

**Comment by nzkfc** [comment]
So they have tried to make it more involved, bascially you get a tank, then you have to fill the tank with air, however it kinda doesn't make sense. What would make more sense is if you had to buy two items, an diving tank and THEN diving gear (the harness/tubes/mask etc) and that you need to use the gear before using the tank, then you can dive.

IRL you buy tanks filled or you fill them yourselves, most of the time from home/store, not at the point of you diving. 

So yeah, you gotta go and add the item to qb-core/shared/items.lua 
https://github.com/qbcore-framework/qb-core/blob/343bc48d95c57db93830830842cc4ebe4c16aaf3/shared/items.lua#L383

Then add the image, which is a picture of a mask gear etc rather then oxygen fill....
https://github.com/qbcore-framework/qb-inventory/blob/main/html/images/diving_tube.png
