### ISSUE TITLE
[BUG] Job

### ISSUE THREAD

**Issue by JustRoys** [qbcore-framework/qb-diving#83]
**Describe the bug**
Police call is set to leo and not the job police

**To Reproduce**
1. qb-diving/server
2. line 33

RegisterNetEvent('qb-diving:server:CallCops', function(coords)
    for _, Player in pairs(QBCore.Functions.GetQBPlayers()) do
        if Player then
            **if Player.PlayerData.job.type == "leo" and Player.PlayerData.job.onduty then**  ---> if Player.PlayerData.job.type == "police" and Player.PlayerData.job.onduty then
                local msg = Lang:t("info.cop_msg")
                TriggerClientEvent('qb-diving:client:CallCops', Player.PlayerData.source, coords, msg)
                local alertData = {
                    title = Lang:t("info.cop_title"),
                    coords = coords,
                    description = msg
                }
                TriggerClientEvent("qb-phone:client:addPoliceAlert", -1, alertData)
            end
        end
    end
end)

**Comment by r0adra93** [comment]
Update your qb-core/shared/jobs.lua to look similar to this for police related jobs
We added the type='leo' to allow for creating multiple departments and just check for the job.type for police and other jobs.
['police'] = {
		label = 'Law Enforcement',
                type = "leo",
		defaultDuty = true,
		offDutyPay = false,
