### ISSUE TITLE
[BUG] Godmode bug

### ISSUE THREAD

**Issue by doublado** [qbcore-framework/qb-diving#90]
**Describe the bug**
When a player have a diving suit on the prop blocks bullets from hitting the players hitbox and in return gives the player "godmode" in the head and chest.

**To Reproduce**
1. Put on the diving suit
2. Shoot the player with a gun in the head or upper chest

**Expected behavior**
The player takes damage

**Fix**
A possible fix to this would be to use the rebreather mask. This is a clothing item and will not give the player "godmode"

**Comment by parham-ebrahim** [comment]
having the same issue . any fixes yet?

**Comment by zSmilleey** [comment]
need a fix
