### ISSUE TITLE
[BUG] Selling

### ISSUE THREAD

**Issue by xxUnknown13xx** [qbcore-framework/qb-diving#95]
When selling the "dendrogyra_coral" or "antipatharia_coral" If you sell 1, you get a random price whatever you made it into. It doesn't matter If you have 10 "antipatharia_coral" you get 1 random price for 10 pieces and I don't think that'r right. Should give you more money.

[2] = {
        item = "antipatharia_coral",
        maxAmount = 100,
        price = math.random(100, 150),
    }

**Comment by Sharkiiie** [comment]
The random price per piece of coral is calculated and set each time the script starts, so every piece of coral sold will sell for the same price.

There is also a bonus given when selling larger amounts of coral, starting at 5 pieces.

**Comment by xxUnknown13xx** [comment]
> The random price per piece of coral is calculated and set each time the script starts, so every piece of coral sold will sell for the same price.
> 
> There is also a bonus given when selling larger amounts of coral, starting at 5 pieces.

I tested few times. in total i had sold 100 pieces. I started doing 10 pieces but i get paid between 100-150 when i sold 10 pieces, then i did 50 pieces and get paid between 100-150$ for 50 pieces. I think the script needs to pay more if you have more pieces and not do one time payment for crazy amount of corals you picked up.

**Comment by Sharkiiie** [comment]
I can take a look at it later to verify the pricing, but if you want it to pay more, update the config :P

**Comment by xxUnknown13xx** [comment]
> I can take a look at it later to verify the pricing, but if you want it to pay more, update the config :P

Thank you:) and I thought bout it but they can take advantage of it if I were to rise the price 😅👀

**Comment by xxUnknown13xx** [comment]
Oh also, is it possible to be able to add a new item - example "Salt"? I wanted to use salt so people can sell the salt to resturant/clubs to make their drinks :)

**Comment by Sharkiiie** [comment]
In general? Yes, you can make any items you like, and do anything with them.

If you need any assistance with creating new items I'd suggest opening a thread in the qbcore discord.

**Comment by xxUnknown13xx** [comment]
> In general? Yes, you can make any items you like, and do anything with them.
> 
> 
> 
> If you need any assistance with creating new items I'd suggest opening a thread in the qbcore discord.

I tried before for help if anyone can help me make it possible lol. I can try again :p

**Comment by Sharkiiie** [comment]
Support is completely community driven, so I'd suggest posting in afternoon or evening, US time. 
You're more likely to get help if you provide a lot of info, post at a good time, and show what you've tried so far.

**Comment by xxUnknown13xx** [comment]
Thank and will do :) but keep me updated bout the other thing tho
